//
//  Workspace.swift
//  CurrencifyManifests
//
//  Created by Vitalii Sosin on 05.03.2024.
//

import ProjectDescription

let workspace = Workspace(
  name: "Currencify",
  projects: ["."],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
