//
//  Workspace.swift
//  CurrencyCoreManifests
//
//  Created by Vitalii Sosin on 05.03.2024.
//

import ProjectDescription

let workspace = Workspace(
  name: "CurrencyCore",
  projects: ["./**"],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
